app/reader/forms.py
# -*— coding:utf-8 -*—
from flask_wtf import FlaskForm
from wtforms import StringField, SubmitField, SelectField, RadioField,PasswordField,IntegerField,TextAreaField,FloatField
from wtforms.validators import DataRequired,Length,Regexp,EqualTo
from wtforms import ValidationError
from app.models import User,Book,Library,choices


class LoginForm(FlaskForm):
    username = StringField('Username',validators=[DataRequired()])
    password = PasswordField('Password',validators=[DataRequired()])
    validcode = StringField('Validcode', validators=[DataRequired()])
    submit = SubmitField('登录')


class RegisterForm(FlaskForm):
    username = StringField('Username', validators=[DataRequired()])
    password = PasswordField('Password', validators=[DataRequired(),EqualTo('password2',message='密码不一致.')])
    password2 = PasswordField('Password', validators=[DataRequired()])
    name = StringField('Name',validators=[DataRequired()])
    gender = RadioField('Gender',choices=[('男','男'),('女','女')],default='男')
    id = StringField('Id',validators=[DataRequired()])
    depart = StringField('Depart',validators=[DataRequired()])
    contact = StringField('Contact',validators=[DataRequired()])
    room = StringField('Room',validators=[DataRequired()])
    avata = StringField('Avata', validators=[])
    submit = SubmitField('注册')

    def validate_username(self,field):
        if User.query.filter_by(username=field.data).first():
            raise ValidationError('用户名已存在')


class AddBookForm(FlaskForm):
    book_id = StringField('Book_id',validators=[DataRequired()])
    isbn = StringField('ISBN', validators=[DataRequired()])
    name = StringField('Name', validators=[DataRequired()])
    author = StringField('Author', validators=[DataRequired()])
    press = StringField('Press', validators=[DataRequired()])
    choices = choices
    category = SelectField('Category', validators=[DataRequired()],choices=choices,coerce=str,default=0)
    location = StringField('Location', validators=[DataRequired()])
    brefintro = TextAreaField('Brefintro', validators=[DataRequired()])
    cover = StringField('Avata', validators=[])
    submit = SubmitField('提交')

    flag = 0
    def validate_isbn(self,field):
        if Book.query.filter_by(isbn=field.data).first():
            self.flag = 1
            raise ValidationError('该ISBN的图书已经存在')

    def validate_book_id(self,field):
        if Library.query.filter_by(book_id=field.data).first():
            self.flag = 2
            raise ValidationError('该图书编号的图书已经存在')

class EditBookForm(FlaskForm):
    isbn = StringField('ISBN', validators=[DataRequired()])
    name = StringField('Name', validators=[DataRequired()])
    author = StringField('Author', validators=[DataRequired()])
    press = StringField('Press', validators=[DataRequired()])
    category = StringField('Category', validators=[DataRequired()])
    brefintro = TextAreaField('Brefintro', validators=[DataRequired()])
    submit = SubmitField('提交')


class SearchBookForm(FlaskForm):
    choices = [('1','书名'),('2','作者'),('3','ISBN')]
    option = SelectField('Option',validators=[DataRequired()],choices=choices,coerce=str)
    key = StringField('key',validators=[DataRequired()])
    submit = SubmitField('提交')

class SearchUserForm(FlaskForm):
    choices = [('1','姓名'),('2','联系方式'),('3','证件号')]
    option = SelectField('Option',validators=[DataRequired()],choices=choices,coerce=str)
    key = StringField('key',validators=[DataRequired()])
    submit = SubmitField('提交')

class AdminUserForm(FlaskForm):
    username = StringField('Name', validators=[DataRequired()])
    name = StringField('Name', validators=[DataRequired()])
    gender = StringField('Gender', validators=[])
    id = StringField('Id', validators=[])
    depart = StringField('Depart', validators=[DataRequired()])
    post = StringField('Post', validators=[])
    contact = StringField('Contact', validators=[DataRequired()])
    room = StringField('Room', validators=[DataRequired()])
    submit = SubmitField('确认修改')

class AdminPasswdForm(FlaskForm):
    password = PasswordField('Password', validators=[DataRequired(), EqualTo('password2', message='密码不一致')])
    password2 = PasswordField('Password', validators=[DataRequired()])
    submit = SubmitField('确认修改')


class SysSetForm(FlaskForm):
    maxuser = StringField('Maxuser', validators=[DataRequired()])
    maxbook = StringField('Maxbook', validators=[DataRequired()])
    maxtime = StringField('Maxtime', validators=[DataRequired()])
    submit = SubmitField('确认修改')


class WantEditForm(FlaskForm):
    name = StringField('Name', validators=[DataRequired()])
    author = StringField('Author', validators=[DataRequired()])
    press = StringField('Press', validators=[DataRequired()])
    choices = choices
    category = SelectField('Category', validators=[DataRequired()], choices=choices, coerce=str, default=0)
    price = FloatField('Price', validators=[DataRequired()])
    submit = SubmitField('提交')

app/reader/__init__.py
# -*— coding:utf-8 -*—
from flask import Blueprint

reader = Blueprint('reader',__name__)

from . import forms, views, errors

app/reader/views.py
# -*— coding:utf-8 -*—
from flask import render_template,request,session,redirect,url_for,abort,flash,json,jsonify
from flask_login import login_required,current_user,login_user,logout_user
from . import reader
from .forms import LoginForm,RegisterForm,AddBookForm,EditBookForm,SearchBookForm,\
    SearchUserForm,AdminUserForm,AdminPasswdForm,SysSetForm,WantEditForm
from app import db
from app.models import User,Book,Library,Request,SysInfo,Want,Statics,category,choices, Log, VoteChoice,Vote,VoteRecord
from sqlalchemy import or_,and_
from datetime import datetime

# ------------------------------ 渲染页面路由 --------------------------------#
# 渲染读者首页
@reader.route('/index',methods=['GET','POST'])
@login_required
def index():
    form = SearchBookForm()
    return render_template('reader/index.html',form=form)

# 渲染读者个人信息页面
@reader.route('/info/user',methods=['GET','POST'])
@login_required
def user():
    form = AdminUserForm()
    if form.validate_on_submit():
        user = User.query.filter_by(username=current_user.username).first()
        user.name = form.name.data
        user.depart = form.depart.data
        user.post = form.post.data
        user.contact = form.contact.data
        user.room = form.room.data
        db.session.commit()
        flash("修改成功")
        return redirect(url_for('reader.user'))
    form.username.data = current_user.username
    form.name.data = current_user.name
    form.gender.data = current_user.gender
    form.id.data = current_user.id
    form.depart.data = current_user.depart
    form.post.data = current_user.post
    form.contact.data = current_user.contact
    form.room.data = current_user.room
    return render_template('reader/user.html',form=form)

# 渲染读者修改密码页面
@reader.route('/info/userpasswd',methods=['GET','POST'])
@login_required
def userpasswd():
    form = AdminPasswdForm()
    if request.method == 'POST':
        if form.validate_on_submit():
            user = User.query.filter_by(username=current_user.username).first()
            user.password = form.password.data
            db.session.commit()
            flash('修改成功')
            return redirect(url_for('reader.userpasswd'))
        else:
            flash('输入密码不一致')
    return render_template('reader/userpasswd.html',form=form)


# 渲染图书归还/转借页面
@reader.route('/bookmanage/mybook',methods=['GET','POST'])
@login_required
def mybook():
    return render_template('reader/mybook.html')

# 渲染图书借阅申请页面
@reader.route('/bookmanage/myrequest',methods=['GET','POST'])
@login_required
def myrequest():
    return render_template('reader/myrequest.html')

# 渲染读者想看编辑页面
@reader.route('/query/wantsedit',methods=['GET','POST'])
@login_required
def wantsedit():
    form = WantEditForm()
    if form.validate_on_submit():
        date = datetime.now().timestamp()
        want = Want(name=form.name.data,author=form.author.data,press=form.press.data,
                    category=form.category.data,sale=form.price.data,requester=current_user.id,date=date)
        db.session.add(want)
        db.session.commit()
        flash('提交成功')
        return redirect(url_for('reader.wantsedit'))
    return render_template('reader/wantsedit.html',form=form)

# 渲染读者提交想看图书列表页面
@reader.route('/query/wantsbook',methods=['GET','POST'])
@login_required
def wantsbook():
    return render_template('reader/wantsbook.html')


# 地理天气
@reader.route('/geoweather/geoweather',methods=['GET','POST'])
@login_required
def geoweather():
    return render_template('reader/geoweather.html')

@reader.route('/geoweather/geoweatherframe',methods=['GET','POST'])
@login_required
def geoweatherframe():
    return render_template('reader/geoweatherframe.html')

# --------------------------------- 天气api --------------------------------#
@reader.route('/api/weather',methods=['GET','POST'])
@login_required
def weather_api():
    import requests
    url = "https://devapi.qweather.com/v7/weather/3d?key=e535cf0229d64262ac09a4c1c2503ba4&location=116.41,39.92"  #换成你自己的key
    res = requests.get(url).json()
    result = {
        "days": [
            {
                "tempmin": res["daily"][0]["tempMin"],
                "tempmax": res["daily"][0]["tempMax"],
                "day": res["daily"][0]["fxDate"],
                "sky": res["daily"][0]["textDay"],
                "wind": res["daily"][0]["windDirDay"],
                "icon": res["daily"][0]["iconDay"],
            },
            {
                "tempmin": res["daily"][1]["tempMin"],
                "tempmax": res["daily"][1]["tempMax"],
                "day": res["daily"][1]["fxDate"],
                "sky": res["daily"][1]["textDay"],
                "wind": res["daily"][1]["windDirDay"],
                "icon": res["daily"][1]["iconDay"]
            },
            {
                "tempmin": res["daily"][2]["tempMin"],
                "tempmax": res["daily"][2]["tempMax"],
                "day": res["daily"][2]["fxDate"],
                "sky": res["daily"][2]["textDay"],
                "wind": res["daily"][2]["windDirDay"],
                "icon": res["daily"][2]["iconDay"]
            }

        ]
    }
    return jsonify(result)


# 参加投票
@reader.route('/user/dovote', methods=['GET','POST'])
@login_required
def dovote():
    if request.method == "GET":
        vote = Vote.query.first()
        total_choice = vote.total_choice
        max_choice = vote.max_choice
        vote_choices = VoteChoice.query.filter_by(vote_id=vote.id).all()
        choices = []
        print('xxxxxxxxxxxxx')
        for vote_choice in vote_choices:
            choices.append(vote_choice.choice)
        return render_template('reader/dovote.html', title=vote.title, content=vote.content,
                               total_choice=total_choice, max_choice=max_choice, choices=choices)
    else:
        vote = Vote.query.first()
        vote_records = VoteRecord.query.filter(and_(VoteRecord.user_id==current_user.id,VoteRecord.vote_id==vote.id)).all()
        if vote_records:
            flash('您已参加过此投票，不能再投')
            return redirect(url_for('reader.dovote',title=vote.title))
        if vote.max_choice == 1:
            choice = request.form['schoice']
            new_record = VoteRecord(user_id=current_user.id,vote_id=vote.id,result=choice,date=datetime.now())
            db.session.add(new_record)
            db.session.commit()
        else:
            count = 0
            # 判断选项有没有超过最大可选数
            for i in range(vote.total_choice):
                index = 'mchoice' + str(i+1)
                try:
                    if request.form[index] == 'on':
                        count = count + 1
                except:
                    pass
            if count > vote.max_choice:
                flash('您的选项不能超过' + str(vote.max_choice) + '个')
                return redirect(url_for('reader.dovote', title=vote.title))
            for i in range(vote.total_choice):
                index = 'mchoice' + str(i+1)
                try:
                    if request.form[index] == 'on':
                        new_record = VoteRecord(user_id=current_user.id, vote_id=vote.id,
                                                result=i+1, date=datetime.now())
                        db.session.add(new_record)
                        db.session.commit()
                except:
                    pass
        flash('投票成功')
        return redirect(url_for('reader.dovote',title=vote.title))



# ------------------------------ 数据 api --------------------------------#
# 返回当前登录的用户名，用于标题栏动态显示
@reader.route('/api/username',methods=['GET','POST'])
@login_required
def username_api():
    return jsonify({'username':current_user.username})

# 返回全部图书信息，用于渲染全部图书信息表格
@reader.route('/api/booklist',methods=['GET','POST'])
@login_required
def booklist_api():
    # 列出所有书目
    booklist= Book.query.all()
    data = []
    i = 1
    for item in booklist:
        # 得到每一本书的存量
        library = Library.query.filter_by(isbn_id=item.isbn).all()
        total = len(library)
        library = Library.query.filter(and_(Library.isbn_id==item.isbn,Library.status==0,Library.readyto_borrow == 0)).all()
        free = len(library)
        cg = ''
        for cat in choices:
            if item.category == cat[0]:
                cg = cat[1]
        data_row = {"sno":i,"isbn":item.isbn,"name":item.name,"author":item.author,
                    "press":item.press,"category":cg,"location":item.location,
                    "total":total,"free":free}
        i =i+1
        data.append(data_row)
    count = len(booklist)
    result = {
        "code": 0,
        "msg": "",
        "count": count,
        "data":data
    }
    return jsonify(result)

# 获取图书信息，用于弹出层显示当前图书信息
@reader.route('/api/bookedit',methods=['GET','POST'])
@login_required
def bookedit_api():
    isbn = request.get_data().decode().split('=')[1]
    book = Book.query.filter_by(isbn=isbn).first()
    cg = ''
    for cat in choices:
        if book.category == cat[0]:
            cg = cat[1]
    if book:
        result = {"isbn": book.isbn,
              "name": book.name,
              "author": book.author,
              "press": book.press,
              "category": cg,
              "location": book.location,
              "intro": book.intro,
              "cover":book.cover}
    return jsonify(result)


# 用于获取当前图书的借阅详情（此路由删去）
@reader.route('/api/bookdetail',methods=['GET','POST'])
@login_required
def bookdetail_api():
    isbn = request.get_data().decode().split('=')[1]
    book = Book.query.filter_by(isbn=isbn).first()
    library = Library.query.filter(and_(Library.isbn_id==isbn,Library.status)).all()
    data = []
    for item in library:
        borrower = User.query.filter_by(id=item.borrower_id).first()
        borrower = borrower.name
        date = item.start_date
        date = datetime.fromtimestamp(date).strftime("20%y-%m-%d")
        row = {"bookname": book.name,
               "author": book.author,
               "press": book.press,
               "borrower": borrower,
               "date": date}

app/templates/reader/base.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>图书管理系统</title>
    <link rel="stylesheet" type="text/css" href="../../static/layui/css/layui.css">
    <script type="text/javascript" href="../../static/bootstrap/jquery.min.js"></script>
    <script type="text/javascript" href="../../static/layui/layui.js"></script>
    <script type="text/javascript" href="../../static/main.js"></script>
    <link rel="icon" href="../../static/img/favicon.ico" type="image/x-icon">
</head>
<body class="layui-layout-body" style="background-image: url('../../static/img/bg.png');background-size: 100%">
<div class="layui-layout layui-layout-admin">
    <!-- 页面头部 -->
    <div class="layui-header layui-bg-blue" style="background: #134556">
        <div class="layui-logo layui-layout-left">
            <a class="layui-logo" href="/reader/index">
                <div class="layui-row">
                    <div class="layui-row layui-col-md3" style="text-align: right"><img src="../../static/img/logo.png" style="height: 20px;width: 20px;"></div>
                    <div class="layui-row layui-col-md8"><h3 style="color: #e6e6e6">图书管理系统</h3></div>
                </div>
            </a>
        </div>
        <ul class="layui-nav layui-layout-right">
            <li class="" style="display: inline-block;vertical-align: middle">
                <a href="#">
                    <img id="headavata" src="" class="layui-nav-img">
                </a>
            </li>
            <li class="layui-nav-item">
                <a href="#"><p id="username"></p></a>
                <dl class="layui-nav-child">
                    <a href="{{ url_for('reader.user') }}">个人信息</a>
                    <a href="{{ url_for('reader.userpasswd') }}">修改密码</a>
                </dl>
            </li>
            <li class="layui-nav-item">
                <a href="{{ url_for('main.logout') }}">退出</a>
            </li>
        </ul>
    </div>
    <!-- 侧边导航栏 -->
    <div class="layui-side layui-bg-red">
        <div class="layui-side-scroll layui-bg-red" style="background: #333">
            <ul class="layui-nav layui-nav-tree layui-bg-red" style="background: #333">
                <li class="layui-nav-item">
                    <a href="javascript:;">&nbsp&nbsp&nbsp&nbsp&nbsp<i class="layui-icon layui-icon-user"></i>&nbsp个人中心</a>
                    <dl class="layui-nav-child">
                        <dd class="layui-this">
                            <a class="layui-bg-blue" href="{{ url_for('reader.user') }}">&nbsp&nbsp&nbsp&nbsp&nbsp个人信息</a>
                        </dd>
                    </dl>
                </li>

                <li class="layui-nav-item">
                    <a href="javascript:;">&nbsp&nbsp&nbsp&nbsp&nbsp<i class="layui-icon layui-icon-form"></i>&nbsp图书借还</a>
                    <dl class="layui-nav-child">
                        <dd class="layui-this">
                            <a class="layui-bg-blue" href="{{ url_for('reader.mybook') }}">&nbsp&nbsp&nbsp&nbsp&nbsp我的图书</a>
                        </dd>
                        <dd class="layui-this">
                            <a class="layui-bg-blue" href="{{ url_for('reader.myrequest') }}">&nbsp&nbsp&nbsp&nbsp&nbsp借阅申请</a>
                        </dd>
                    </dl>
                </li>

                <!--新增功能-->
                <li class="layui-nav-item">
                    <a href="javascript:;">&nbsp&nbsp&nbsp&nbsp&nbsp<i class="layui-icon layui-icon-survey"></i>&nbsp位置天气</a>
                    <dl class="layui-nav-child">
                        <dd class="layui-this">
                            <a class="layui-bg-blue" href="{{ url_for('reader.geoweather') }}">&nbsp&nbsp&nbsp&nbsp&nbsp地理位置与天气</a>
                        </dd>
                    </dl>
                </li>

                <li class="layui-nav-item">
                    <a href="javascript:;">&nbsp&nbsp&nbsp&nbsp&nbsp<i class="layui-icon layui-icon-survey"></i>&nbsp投票问卷</a>
                    <dl class="layui-nav-child">
                        <dd class="layui-this">
                            <a class="layui-bg-blue" href="{{ url_for('reader.dovote') }}">&nbsp&nbsp&nbsp&nbsp&nbsp参加投票</a>
                        </dd>
                    </dl>
                </li>
            </ul>
        </div>
    </div>
    <!-- 主体内容 -->
    <div class="layui-body">
        <div class="layui-row">
            <div class="layui-card-header">
                <h2>{% block card_header %}{% endblock %}</h2>
            </div>
            <div class="layui-fluid">
                <div class="layui-card-body">
                    {% block card_body %}
                    {% endblock %}
                </div>
            </div>
        </div>
    </div>
    <!-- 页面底部 -->
    <div class="layui-footer">
        <p>2022 蚌埠组 蜀ICP备2022014596号-1</p>
    </div>
</div>

<script src="../../static/layui/layui.js"></script>
<script src="../../static/jquery/jquery.min.js"></script>
<script>
    layui.use('element',function (){
        var element = layui.element
        element.init()
    })
</script>

<!-- 标题栏显示当前登录的用户名 -->
<script>
    $.post('{{ url_for('main.username_api') }}',function (data){
        $("#username").text(data.username)
        username = data.username;
        $.post('{{ url_for('main.get_avata_url_api') }}',{username:username},function (str){
            avata_url = str.url;
            console.log(avata_url)
            if(avata_url == 'lost')
            {
                avata_url = "../../static/img/avata/defaultavata.jpg"
                $("#headavata").attr("src",avata_url)
            }
            else
                $("#headavata").attr("src",avata_url)
        })
    })
</script>

{% block script %}
{% endblock %}

{% block outest %}
{% endblock %}

</body>
</html>

app/templates/reader/dovote.html
{% extends 'reader/base.html' %}

{% block card_header %}
<span><a href="/index"> 投票问卷 / </a></span><span>参加投票</span>
{% endblock %}


{% block card_body %}
<div class="add-vote" style="margin: 10px 50px">
        <p class="layui-text">
            投票标题：{{ title }}
        </p>
        <p class="layui-code" style="height: 100px; overflow: auto;">
            <span class="run">{{ content }}</span>
        </p>
        <p class="layui-text">
            提示：最多选择{{ max_choice }}个选项
        </p>
        <form class="layui-form" method="post">
            <div class="layui-form-item">
                <div class="layui-input-inline">
                    {% if max_choice == 1 %}
                        {% for i in range(total_choice) %}
                            {% if i == 0 %}
                                <input type="radio" id="schoice" name="schoice" value="{{ i + 1 }}" title="{{ choices[i] }}" checked="">
                            {% else %}
                                <input type="radio" id="schoice" name="schoice" value="{{ i + 1 }}" title="{{ choices[i] }}">
                            {% endif %}
                        {% endfor %}
                    {% else %}
                        {% for i in range(total_choice) %}
                            <input type="checkbox" id="mchoice" name="mchoice{{ i + 1 }}" lay-skin="primary" title="{{ choices[i] }}" >
                        {% endfor %}
                    {% endif %}
                </div>
            </div>
            <div class="layui-input-inline">
                <input class="layui-btn layui-btn-normal" type="submit" name="submit" value="投票" id="dovote" style="margin: 0 160px">
            </div>
        </form>
    </div>
{% endblock %}

{% block script %}


<script src="../static/layui/layui.js"></script>
<script>
layui.use(['layer'], function(){
    var layer = layui.layer
    {% for message in get_flashed_messages() %}
        layer.msg('{{ message }}');
    {% endfor %}
});

layui.use('form', function(){
  var form = layui.form;
});

layui.use('laydate', function(){
    var laydate = layui.laydate;

    //执行一个laydate实例
    laydate.render({
        elem: '#enddate', //指定元素
        type: 'datetime'
    });
});
</script>

<script>
    var choices = '';
    var index = 1;
    $("#addchoice").on('click',function (){
        if($("#choiceinput").val() != '')
        {
            choices = choices + $("#choiceinput").val() + '^';
            console.log(choices);
            $("#newchoices").append('<p>' + '选项' + index.toString() + ': ' + $("#choiceinput").val() + '</p>')
            $("#subchoices").val(choices);
            $("#choiceinput").val('');
            index++;
        }
    })
</script>
{% endblock %}

app/templates/reader/geoweather.html
{% extends 'reader/base.html' %}

{% block card_header %}
<span><a href="/index"> 位置天气 / </a></span><span>位置天气</span>
{% endblock %}


{% block card_body %}
    <div class="layui-row my-weather" style="height: 120px; width: 100%">
        <div class="layui-row layui-col-md2">
            <div style="text-align: center; padding: 10px 0">
                <h2>成都天气</h2>
                <p id="today" style="color: #2D93CA; padding: 5px 0"></p>
            </div>
        </div>
        <div class="layui-row layui-col-md2">
            <div class="layui-row">
                <div class="layui-row layui-col-md6">
                    <img src="../static/weather/icons/301.svg" alt="QWeather1" width="48" height="48" id="Qweather1">
                </div>
                <div class="layui-row layui-col-md6">
                    <p id="day1"></p>
                    <p id="temp1"></p>
                    <p id="wind1"></p>
                </div>
            </div>
        </div>
        <div class="layui-row layui-col-md2">
            <div class="layui-row">
                <div class="layui-row layui-col-md6">
                    <img src="../static/weather/icons/301.svg" alt="QWeather2" width="48" height="48" id="Qweather2">
                </div>
                <div class="layui-row layui-col-md6">
                    <p id="day2"></p>
                    <p id="temp2"></p>
                    <p id="wind2"></p>
                </div>
            </div>
        </div>
        <div class="layui-row layui-col-md2">
            <div class="layui-row">
                <div class="layui-row layui-col-md6">
                    <img src="../static/weather/icons/301.svg" alt="QWeather3" width="48" height="48" id="Qweather3">
                </div>
                <div class="layui-row layui-col-md6">
                    <p id="day3"></p>
                    <p id="temp3"></p>
                    <p id="wind3"></p>
                </div>
            </div>
        </div>
    </div>
    <div class="my-map" style="width: 100%; height: 650px">
        <iframe width=100% height=100% frameborder=0 scrolling=auto src="{{url_for('reader.geoweatherframe')}}"></iframe>
    </div>
{% endblock %}

{% block script %}

<script src="../static/layui/layui.js"></script>
<script>
layui.use(['layer'], function(){
    var layer = layui.layer
    {% for message in get_flashed_messages() %}
        layer.msg('{{ message }}');
    {% endfor %}
});

layui.use('form', function(){
  var form = layui.form;
});

$.get("{{ url_for('reader.weather_api') }}", function (res){
    console.log(res.days)
    var day1 = res.days[0]
    var day2 = res.days[1]
    var day3 = res.days[2]
    var url = 'http://127.0.0.1:5000/static/weather/icons/' + day1.icon + '.svg'
    console.log(url)
    $("#Qweather1").attr("src", url)
    $("#day1").text(day1.day)
    $("#temp1").text(day1.tempmin + ' ~ ' + day1.tempmax + '°C')
    $("#wind1").text(day1.wind)
    $("#today").text(day1.sky)

    var url = 'http://127.0.0.1:5000/static/weather/icons/' + day2.icon + '.svg'
    $("#Qweather2").attr('src', url)
    $("#day2").text(day2.day)
    $("#temp2").text(day2.tempmin + ' ~ ' + day2.tempmax + '°C')
    $("#wind2").text(day2.wind)

    var url = 'http://127.0.0.1:5000/static/weather/icons/' + day3.icon + '.svg'
    $("#Qweather3").attr('src', url)
    $("#day3").text(day3.day)
    $("#temp3").text(day3.tempmin + ' ~ ' + day3.tempmax + '°C')
    $("#wind3").text(day3.wind)
})
</script>

{% endblock %}

app/templates/reader/geoweatherframe.html
<!DOCTYPE html>
<html>
<head>
	<meta http-equiv="Content-Type" content="text/html; charset=utf-8" />
	<meta name="viewport" content="initial-scale=1.0, user-scalable=no" />
	<style type="text/css">
	body, html,#allmap {width: 100%;height: 100%;overflow: hidden;margin:0;font-family:"微软雅黑";}
	</style>
	<script type="text/javascript" src="//api.map.baidu.com/api?v=2.0&ak=hjVsSHM0joktSaurPFPvwBXK9aqUywwH"></script>
	<title>地图展示</title>
</head>
<body>
	<div id="allmap"></div>
</body>
</html>
<script type="text/javascript">
	// 百度地图API功能
	var map = new BMap.Map("allmap");    // 创建Map实例
	map.centerAndZoom(new BMap.Point(103.993831, 30.769334), 15);  // 初始化地图,设置中心点坐标和地图级别
	//添加地图类型控件
	map.addControl(new BMap.MapTypeControl({
		mapTypes:[
            BMAP_NORMAL_MAP,
            BMAP_HYBRID_MAP
        ]}));
	map.setCurrentCity("成都");          // 设置地图显示的城市 此项是必须设置的
	map.enableScrollWheelZoom(true);     //开启鼠标滚轮缩放
</script>